name: Deploy landing page

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
  EMAILJS_TEMPLATE_ID: ${{ secrets.EMAILJS_TEMPLATE_ID }}
  EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
